<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @file
 * Module file for Housing Schemes Services.
 * Contains the resource declarations for the service APIs
 * and other commons functions/hooks. if necessary
 */

/**
 * Implements hook_services_resources().
 * Create service resource for APIs to return the necessary json data.
 */
function dhm_rest_api_services_resources() {
  $resources = array();

//Include the necessary inc files.
  module_load_include('inc', 'dhm_rest_api', 'includes/dhm_rest_api.services');

//Service Apis for contents.
  $resources += dhm_rest_api_resource();

  return $resources;
}
?>